apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: od09ebqom-go 
  janus-idp.io/tekton: od09ebqom-go
  backstage.io/kubernetes-id: od09ebqom-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: od09ebqom-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  